spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  messages:
    basename: messages

  security:
    user:
      name: username
      password: password

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework: info
